version: "3"
services:
  proxy:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./store:/store"
