version: "3.7"

services:
  minio:
    image: minio/minio
    container_name: minio-worker
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=trongnv
      - MINIO_ROOT_PASSWORD=dev@1234
      - MINIO_HTTP_TRACE=output.log
    ports:
      - "9000:9000"
      - "9001:9001"
  # nginx:
  #   image: nginx:1.19.2-alpine
  #   hostname: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   depends_on:
  #     - minio